### ISSUE TITLE
update A and AAAA records in one request

### ISSUE THREAD

**Issue by silentApplause** [SteffenKn/cloudflare-ddns-sync#12]
var records = [{
                name: 'x.y.z',
                type: 'A', 
                proxied: false,             
                priority: 0, 
                content: '1.2.3.4', 
            },
            {
                name: 'x.y.z',
                type: 'AAAA',
                proxied: false, 
                priority: 0, 
                content: '1000::10000', 
           }
        ];
        cddnss.syncRecords(records).then((result) => {
            console.log(result);
        });

  host: 'api.cloudflare.com',
  hostname: 'api.cloudflare.com',
  method: 'PUT',
  path: '/client/v4/zones/***/dns_records/*****',
  statusCode: 400,
  statusMessage: 'Bad Request'

**Comment by SteffenKn** [comment]
Hello silentApplause,
Thank you for creating this issue.

The IPv6 address in your code example seems to be invalid (`1000::10000`) try replacing this line `content: '1000::10000',` with `content: '1000::1000',`.
If it still doesn't work, please tell me which version of cloudflare-ddns-sync you are using.

**Comment by silentApplause** [comment]
I'm using cloudflare-ddns-sync@2.0.2.
I'm using other functions to get my server's IP addresses and using String variable to create the request.    The example above is a mistake.  
it is still not working.

![image](https://user-images.githubusercontent.com/40753924/100031711-3f95f700-2e31-11eb-98e5-0679f5e16cd1.png)

**Comment by SteffenKn** [comment]
So there was an issue with updating records if two records have the same name.
Is that the case in your code?

If that is the case please try again with v2.0.3

<details>
  <summary>If thats not the case I have some questions for you:</summary>
  
Is it working if you call `syncRecord` for each records instead of `syncRecords` for both?

Do you get an error logged or is the result printed but the syncing still did not work?

Also if you have any more tips on how to reproduce the issue I would be happy to hear from you.
</details>

**Comment by silentApplause** [comment]
Problem solved in 2.0.3
Thanks

**Comment by SteffenKn** [comment]
Thanks for reporting the issue.
